name: Push To Test1 Repo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Push to Test1 repo
      env:
        GITHUB_TOKEN: ${{ secrets.personal_github_token }}
      run: |
        git remote add test git@github.com:watchpartyappmain:$GITHUB_TOKEN@github.com/TestingRepo1
        git config --global user.email "watchpartyappmain@gmail.com"
        git config --global user.name "watchpartyappmain"
        git checkout master
        git push -u test master
