name: Push To Test1 Repo
on:
  push:
    branches: [ master ]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      env:
        SOURCE_REPO: "watchpartyappmain/TestingRepo"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "watchpartyappmain/TestingRepo1"
        DESTINATION_BRANCH: "master"
        GITHUB_TOKEN: ${{ secrets.personal_github_token }}
      with:
        source_repo: "watchpartyappmain/TestingRepo1"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.personal_github_token }}
        access_token: ${{ secrets.personal_github_token }}
